version: "3.3"
services:
  bank_tasks:
    build: .
    container_name: bank_tasks
    restart: always
    environment:
      - TZ=Europe/Moscow
    env_file:
      - ./source/.env
    networks:
      - uprav_cfu_network

networks:
  uprav_cfu_network:
    external: true
