version: "3.3"
services:
  bank_scrapper:
    build: .
    image: bank_scrapper
    container_name: bank_scrapper
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /home/user/.volumes/bank_scrapper/source:/source:rw
    tty: true
    working_dir: /source
    command: ["python", "main.py"]